import Anthropic     from '@anthropic-ai/sdk'
import { supabaseAdmin, getLatestObs } from '@/lib/supabase'

/**
 * Neutral fallback copy used when AI generation is not configured (or fails).
 *
 * The previous version of this string contained specific numeric claims
 * ("CSHI rose to 72.4", "permits +8.3% MoM", "$4.8B in new awards") that
 * were stale the moment they were written. Public-facing copy must never
 * present stale numerics as if they were the current week's read — so this
 * is intentionally generic. Provenance fields (`source`, `live`,
 * `configured`) on the API response make the fallback state explicit.
 */
export const STATIC_BRIEF =
  'Weekly Brief unavailable — live AI generation is not configured for this deployment. ' +
  'See /api/status for the configuration state, or set ANTHROPIC_API_KEY in the runtime ' +
  'environment to enable weekly intelligence briefs.'

export type BriefSource = 'ai' | 'static-fallback'

export interface BriefResult {
  brief:        string
  generatedAt:  string
  source:       BriefSource
  /** True only when the brief was just generated by Claude. */
  live:         boolean
  /** True when ANTHROPIC_API_KEY is present in the runtime environment. */
  configured:   boolean
  /** Set whenever the response is the static fallback rather than fresh AI output. */
  warning?:     string
  /** Underlying error message — never exposes secrets. */
  error?:       string
}

/** True when ANTHROPIC_API_KEY is present in the current process. Never returns the key value. */
export function isWeeklyBriefConfigured(): boolean {
  return Boolean(process.env.ANTHROPIC_API_KEY && process.env.ANTHROPIC_API_KEY.length > 0)
}

const MODEL     = 'claude-sonnet-4-6'
const MAX_TOKENS = 500
const TTL_MS    = 7 * 24 * 60 * 60 * 1000  // 7 days

// ── Data formatting ────────────────────────────────────────────────────────

interface Obs { obs_date: string; value: number }

function formatSeries(label: string, obs: Obs[], unit: string): string {
  if (!obs.length) return `${label}: no data available`
  const last = obs[obs.length - 1]
  const prev = obs[obs.length - 2]
  const mom  = prev
    ? `${((last.value - prev.value) / Math.abs(prev.value) * 100).toFixed(1)}% MoM`
    : 'prior period unavailable'
  return `${label}: ${last.value.toLocaleString('en-US', { maximumFractionDigits: 1 })}${unit} as of ${last.obs_date} (${mom})`
}

async function buildDataBlock(): Promise<{ text: string; snapshot: Record<string, Obs[]> }> {
  const [ttlcons, employment, permits, housing] = await Promise.all([
    getLatestObs('TTLCONS',       3),
    getLatestObs('CES2000000001', 3),
    getLatestObs('PERMIT',        3),
    getLatestObs('HOUST',         3),
  ])

  const snapshot = {
    TTLCONS:       ttlcons       as Obs[],
    CES2000000001: employment    as Obs[],
    PERMIT:        permits       as Obs[],
    HOUST:         housing       as Obs[],
  }

  const text = [
    formatSeries('Total Construction Spending (TTLCONS)',            snapshot.TTLCONS,       ' $M SAAR'),
    formatSeries('Construction Employment (CES2000000001)',           snapshot.CES2000000001, 'K workers'),
    formatSeries('New Residential Building Permits (PERMIT)',         snapshot.PERMIT,        'K units SAAR'),
    formatSeries('Housing Starts (HOUST)',                            snapshot.HOUST,         'K units SAAR'),
  ].join('\n')

  return { text, snapshot }
}

function buildPrompt(dataText: string): string {
  const weekEnding = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
  return `You are a construction market analyst producing a weekly intelligence brief for construction executives and investors.

Using ONLY the data provided below, write a concise brief. Do not invent, estimate, or cite any numbers not explicitly present in the data.

FORMAT (use exactly these three section headers, nothing else):
HEADLINE SIGNAL: [one decisive sentence — the single most significant change in the data]

WHAT MOVED:
• [data-driven observation with specific figure]
• [data-driven observation with specific figure]
• [data-driven observation with specific figure]

WATCH NEXT WEEK:
• [forward-looking implication grounded in the data]
• [forward-looking implication grounded in the data]

Rules:
- Maximum 250 words
- Only use numbers from the provided data
- Write for executives who make capital allocation decisions
- Be specific and actionable

DATA (week ending ${weekEnding}):
${dataText}`
}

// ── Core generation ────────────────────────────────────────────────────────

function fallbackResult(reason: string, configured: boolean): BriefResult {
  return {
    brief:       STATIC_BRIEF,
    generatedAt: new Date().toISOString(),
    source:      'static-fallback',
    live:        false,
    configured,
    warning:     'Live AI weekly brief unavailable; serving neutral fallback copy.',
    error:       reason,
  }
}

export async function generateBrief(): Promise<BriefResult> {
  const configured = isWeeklyBriefConfigured()
  const apiKey     = process.env.ANTHROPIC_API_KEY

  if (!configured || !apiKey) {
    return fallbackResult('ANTHROPIC_API_KEY not set', false)
  }

  let dataText  = ''
  let snapshot: Record<string, Obs[]> = {}
  try {
    const result = await buildDataBlock()
    dataText = result.text
    snapshot = result.snapshot
  } catch (err) {
    console.warn('[weeklyBrief] Data fetch failed, generating without real data:', err)
    dataText = '(no live data available — use your general knowledge of recent market conditions)'
  }

  try {
    const client  = new Anthropic({ apiKey })
    const message = await client.messages.create({
      model:      MODEL,
      max_tokens: MAX_TOKENS,
      messages:   [{ role: 'user', content: buildPrompt(dataText) }],
    })

    const briefText = message.content.find(b => b.type === 'text')
      ? (message.content.find(b => b.type === 'text') as { type: 'text'; text: string }).text.trim()
      : ''

    if (!briefText) throw new Error('Empty response from Claude')

    const generatedAt = new Date().toISOString()

    // Persist — non-blocking, don't fail the request if write fails
    supabaseAdmin.from('weekly_briefs').insert({
      brief_text:    briefText,
      generated_at:  generatedAt,
      data_snapshot: snapshot,
      model:         MODEL,
      source:        'ai',
    }).then(({ error }) => {
      if (error) console.warn('[weeklyBrief] DB write failed:', error.message)
    })

    return {
      brief:       briefText,
      generatedAt,
      source:      'ai',
      live:        true,
      configured:  true,
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    console.error('[weeklyBrief] Claude call failed:', msg)
    return fallbackResult(msg, true)
  }
}

/**
 * Returns a cached AI brief from the database if under 7 days old, otherwise
 * generates a fresh one via Claude. When neither path is available the
 * response is the explicit static-fallback (see `fallbackResult`).
 *
 * `live` is true ONLY when the brief was just generated in this call. Cached
 * AI rows are still real Claude output but are not "this-call live" — the
 * `source` field (`ai` vs `static-fallback`) is the authoritative provenance.
 */
export async function getWeeklyBrief(opts?: { forceRefresh?: boolean }): Promise<BriefResult> {
  const configured = isWeeklyBriefConfigured()

  if (!opts?.forceRefresh) {
    try {
      const cutoff = new Date(Date.now() - TTL_MS).toISOString()
      const { data } = await supabaseAdmin
        .from('weekly_briefs')
        .select('brief_text, generated_at, source')
        .gte('generated_at', cutoff)
        .order('generated_at', { ascending: false })
        .limit(1)
        .single()

      if (data) {
        const dbSource = data.source as string
        const source: BriefSource = dbSource === 'ai' ? 'ai' : 'static-fallback'
        return {
          brief:       data.brief_text as string,
          generatedAt: data.generated_at as string,
          source,
          live:        false,
          configured,
        }
      }
    } catch {
      // No cached brief (PGRST116 "no rows") or Supabase unreachable — generate fresh
    }
  }

  return generateBrief()
}
