import { NextResponse } from "next/server"

export const maxDuration = 10

const EVENTS = [
  {
    id: "census-permits-apr",
    date: "2026-04-17",
    time: "08:30",
    name: "Building Permits & Housing Starts",
    source: "Census Bureau",
    category: "permits",
    importance: "high",
    description: "Monthly residential construction activity report",
    consensus: "1.48M permits (SAAR)",
    prior: "1.46M",
    impact: ["Residential pipeline", "Lumber demand", "Framing contractors"],
  },
  {
    id: "bls-producer-prices-apr",
    date: "2026-04-11",
    time: "08:30",
    name: "Producer Price Index — Construction Materials",
    source: "BLS",
    category: "costs",
    importance: "high",
    description: "Input cost inflation for construction materials and services",
    consensus: "+0.3% MoM",
    prior: "+0.5%",
    impact: ["Bid escalation", "Contract pricing", "Material procurement"],
  },
  {
    id: "bls-jolts-mar",
    date: "2026-04-22",
    time: "10:00",
    name: "JOLTS — Construction Job Openings",
    source: "BLS",
    category: "labor",
    importance: "medium",
    description: "Job openings, hires, and separations in the construction sector",
    consensus: "315K openings",
    prior: "308K",
    impact: ["Labor availability", "Wage pressure", "Project delays"],
  },
  {
    id: "census-construction-spending-mar",
    date: "2026-05-01",
    time: "10:00",
    name: "Construction Spending (March)",
    source: "Census Bureau",
    category: "spending",
    importance: "high",
    description: "Total value put in place for private and public construction",
    consensus: "$2.11T SAAR",
    prior: "$2.09T",
    impact: ["Market size", "Public vs private mix", "GC revenue outlook"],
  },
  {
    id: "bls-employment-apr",
    date: "2026-05-08",
    time: "08:30",
    name: "Employment Situation — Construction Payrolls",
    source: "BLS",
    category: "labor",
    importance: "high",
    description: "Monthly construction employment, hours, and earnings",
    consensus: "+22K construction jobs",
    prior: "+19K",
    impact: ["Workforce supply", "Subcontractor capacity", "Cost inflation"],
  },
  {
    id: "eia-natural-gas-may",
    date: "2026-05-08",
    time: "10:30",
    name: "Natural Gas Storage Report",
    source: "EIA",
    category: "energy",
    importance: "low",
    description: "Weekly natural gas working stock; proxy for heating/energy cost trends",
    consensus: "+62 Bcf",
    prior: "+58 Bcf",
    impact: ["Fuel costs", "HVAC project timing", "Energy-intensive projects"],
  },
  {
    id: "census-permits-may",
    date: "2026-05-15",
    time: "08:30",
    name: "Building Permits & Housing Starts (April)",
    source: "Census Bureau",
    category: "permits",
    importance: "high",
    description: "Monthly residential construction activity report",
    consensus: "1.50M permits (SAAR)",
    prior: "1.48M",
    impact: ["Residential pipeline", "Lumber demand", "Framing contractors"],
  },
  {
    id: "bls-ppi-may",
    date: "2026-05-14",
    time: "08:30",
    name: "Producer Price Index — Construction Materials",
    source: "BLS",
    category: "costs",
    importance: "high",
    description: "Input cost inflation for construction materials and services",
    consensus: "+0.2% MoM",
    prior: "+0.3%",
    impact: ["Bid escalation", "Contract pricing", "Material procurement"],
  },
  {
    id: "fred-senior-loan-q2",
    date: "2026-05-12",
    time: "14:00",
    name: "Senior Loan Officer Opinion (SLOOS)",
    source: "Federal Reserve",
    category: "credit",
    importance: "high",
    description: "Quarterly report on bank lending standards for CRE and construction loans",
    consensus: "Tightening expected to ease",
    prior: "Net 14.2% tightening",
    impact: ["Construction lending", "Project financing", "Developer pipeline"],
  },
  {
    id: "census-new-residential-sales-apr",
    date: "2026-05-22",
    time: "10:00",
    name: "New Residential Sales (April)",
    source: "Census Bureau",
    category: "permits",
    importance: "medium",
    description: "Sales of newly constructed single-family homes",
    consensus: "690K SAAR",
    prior: "678K",
    impact: ["Builder backlog", "Lot supply", "Home completion rates"],
  },
  {
    id: "bea-gdp-q1-adv",
    date: "2026-04-30",
    time: "08:30",
    name: "GDP Advance Estimate — Q1 2026 (Construction Component)",
    source: "BEA",
    category: "spending",
    importance: "high",
    description: "Gross private domestic fixed investment in structures",
    consensus: "+3.2% annualized",
    prior: "+2.8%",
    impact: ["Overall construction demand", "Investment cycle", "Market outlook"],
  },
  {
    id: "bls-cpi-apr",
    date: "2026-04-10",
    time: "08:30",
    name: "Consumer Price Index (March) — Housing Component",
    source: "BLS",
    category: "costs",
    importance: "medium",
    description: "Shelter and housing cost inflation; leads building material inflation",
    consensus: "+0.4% MoM shelter",
    prior: "+0.4%",
    impact: ["Rental construction demand", "Multifamily feasibility", "Owner cost comparison"],
  },
  {
    id: "census-construction-spending-apr",
    date: "2026-06-02",
    time: "10:00",
    name: "Construction Spending (April)",
    source: "Census Bureau",
    category: "spending",
    importance: "high",
    description: "Total value put in place for private and public construction",
    consensus: "$2.13T SAAR",
    prior: "$2.11T",
    impact: ["Market size", "Public vs private mix", "GC revenue outlook"],
  },
  {
    id: "eia-petroleum-weekly",
    date: "2026-04-23",
    time: "10:30",
    name: "Petroleum Status Report",
    source: "EIA",
    category: "energy",
    importance: "low",
    description: "Weekly crude oil and fuel inventories; tracks diesel costs for heavy equipment",
    consensus: "-1.4M barrels",
    prior: "-2.1M barrels",
    impact: ["Fuel costs", "Equipment operation", "Asphalt pricing"],
  },
  {
    id: "bls-jolts-apr",
    date: "2026-05-21",
    time: "10:00",
    name: "JOLTS — Construction Job Openings (April)",
    source: "BLS",
    category: "labor",
    importance: "medium",
    description: "Job openings, hires, and separations in the construction sector",
    consensus: "322K openings",
    prior: "315K",
    impact: ["Labor availability", "Wage pressure", "Project delays"],
  },
  {
    id: "census-permits-jun",
    date: "2026-06-18",
    time: "08:30",
    name: "Building Permits & Housing Starts (May)",
    source: "Census Bureau",
    category: "permits",
    importance: "high",
    description: "Monthly residential construction activity report",
    consensus: "1.52M permits (SAAR)",
    prior: "1.50M",
    impact: ["Residential pipeline", "Lumber demand", "Framing contractors"],
  },
  {
    id: "fed-fomc-may",
    date: "2026-05-06",
    time: "14:00",
    name: "FOMC Rate Decision",
    source: "Federal Reserve",
    category: "credit",
    importance: "high",
    description: "Federal funds rate decision; drives construction loan and mortgage rates",
    consensus: "Hold at 4.25–4.50%",
    prior: "4.25–4.50%",
    impact: ["Construction financing cost", "Developer feasibility", "Cap rates"],
  },
]

const CATEGORIES = [
  { id: "all",      label: "All Events" },
  { id: "permits",  label: "Permits & Starts" },
  { id: "costs",    label: "Cost Indices" },
  { id: "labor",    label: "Labor Data" },
  { id: "spending", label: "Spending Data" },
  { id: "credit",   label: "Credit & Rates" },
  { id: "energy",   label: "Energy" },
]

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url)
  const category = searchParams.get("category") ?? "all"

  const events = category === "all"
    ? EVENTS
    : EVENTS.filter(e => e.category === category)

  const sorted = [...events].sort((a, b) => a.date.localeCompare(b.date))

  return NextResponse.json({
    events: sorted,
    categories: CATEGORIES,
    total: sorted.length,
    period: "Next 90 days",
    generated_at: new Date().toISOString(),
  }, {
    headers: { "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=7200" }
  })
}
