import type { Metadata } from "next"
import { Nav } from "@/app/components/Nav"
import { NLQInterface } from "@/app/dashboard/components/NLQInterface"
import { color, font, radius, type as typeScale } from "@/lib/theme"

export const metadata: Metadata = {
  title:       "Ask the Construction Economy — ConstructAIQ",
  description: "AI-powered queries across Census, BLS, FRED, USASpending, and satellite data. Every answer cited.",
}

const SYS  = font.sys
const MONO = font.mono

export default function AskPage() {
  return (
    <div style={{ background: color.bg0, minHeight: "100vh", fontFamily: SYS }}>
      <Nav />

      <main style={{
        maxWidth:  760,
        margin:    "0 auto",
        padding:   "64px 24px 80px",
      }}>
        {/* Header */}
        <div style={{ marginBottom: 36 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 12 }}>
            <h1 style={{
              ...typeScale.h3,
              color:  color.t1,
              margin: 0,
            }}>
              Ask the Construction Economy
            </h1>
            <span style={{
              fontFamily:    MONO,
              fontSize:      10,
              fontWeight:    600,
              color:         color.blue,
              background:    color.blueDim,
              border:        `1px solid ${color.blue}33`,
              borderRadius:  radius.xs,
              padding:       "2px 8px",
              letterSpacing: "0.08em",
              flexShrink:    0,
              alignSelf:     "center",
            }}>
              AI
            </span>
          </div>

          <p style={{
            ...typeScale.body,
            color:     color.t3,
            margin:    0,
            maxWidth:  600,
          }}>
            AI-powered queries across Census, BLS, FRED, USASpending, and satellite data.
            Every answer cited.
          </p>
        </div>

        {/* NLQ interface */}
        <NLQInterface />

        {/* Methodology note */}
        <div style={{
          marginTop:    28,
          padding:      "16px 20px",
          background:   color.bg1,
          border:       `1px solid ${color.bd1}`,
          borderRadius: radius.lg,
        }}>
          <p style={{
            fontFamily:  MONO,
            fontSize:    11.5,
            color:       color.t4,
            margin:      0,
            lineHeight:  1.7,
            letterSpacing: "0.01em",
          }}>
            Answers are generated by Claude (Anthropic) using only data from US government sources.
            Every statistic links to its source. Rate limited to 10 queries/hour to prevent abuse.
            Not financial advice.
          </p>
        </div>
      </main>
    </div>
  )
}
